### ISSUE TITLE
Stuck after updating to clover 5124

### ISSUE THREAD

**Issue by syah769** [CloverHackyColor/CloverBootloader#258]
![IMG_20201012_232621](https://user-images.githubusercontent.com/37147869/95764737-71b92280-0ce3-11eb-8d87-3cb00f7e6ef7.jpg)

What's the problem? I updated to clover 5124 and it stuck and cannot boot to the home menu

**Comment by chriseg93** [comment]
Got the same issue, it was working somewhat with the pre-release but now I'm just stuck at the apple logo.

**Comment by syah769** [comment]
> Got the same issue, it was working somewhat with the pre-release but now I'm just stuck at the apple logo.

At least you're booting until apple logo. But mine do not stuck at the apple logo. Omg, what happened 😭😭

**Comment by Noodle05** [comment]
Same thing here. Before it should clover menu, an error message No returned found from DataHubDxe.efi. Not sure if it's related.

**Comment by mgrandinetti** [comment]
after UPDATE I lock my system to
LOG:EXITSB:START

seem a problem with bootx64.efi. If I change this all works again

thank in advance

**Comment by hyperNURb** [comment]
![91A1141A-4828-460E-BBB1-B57FA3010F15](https://user-images.githubusercontent.com/59742/95782958-2bf35e80-0cd1-11eb-847a-00d699d20c06.jpeg)

I get the same issue

**Comment by hyperNURb** [comment]
> after UPDATE I lock my system to
> LOG:EXITSB:START
> 
> seem a problem with bootx64.efi. If I change this all works again
> 
> thank in advance

How did you change the bootx64.efi?

**Comment by syah769** [comment]
> after UPDATE I lock my system to
> LOG:EXITSB:START
> 
> seem a problem with bootx64.efi. If I change this all works again
> 
> thank in advance

May i know how do you change the bootx64.efi?

**Comment by chriseg93** [comment]
You just download the bootx64.efi from release 5123 and replace it with the one it has currently

@hyperNURb @syah769

**Comment by syah769** [comment]
> You just download the bootx64.efi from release 5123 and replace it with the one it has currently
> 
> @hyperNURb @syah769

How to replace it? Because my screen was blank

**Comment by chriseg93** [comment]
My guy, I'm not an expert in this, but you should have backups just in case because you just never know what can happen..If you have no other macOS software, then you can do it through a virtual machine on Windows.

@syah769

**Comment by syah769** [comment]
> My guy, I'm not an expert in this, but you should have backups just in case because you just never know what can happen..If you have no other macOS software, then you can do it through a virtual machine on Windows. That's how I would do it, not too sure if there's another way. Sorry.
> 
> @syah769

Alright, thanks for your advice

**Comment by i0ntempest** [comment]
+1 stuck after updating. I get "not found returned from datahubdxe.efi", then after selecting Catalina it sticks at "[EB]#LOG:EXITBS:START]".

**Comment by ifamed** [comment]
> tuck after updating. I get "not found returned from datahubdxe.efi", then after selecting Catalina it sticks at "[EB]#LOG:EXITBS:START]".

try remove datahubdxe.efi and this error will disappear

**Comment by mwahh** [comment]
I am, as yet, unable to boot Catalina with either 5123 or 5124.  5123 starts to boot and then freezes early in the boot process.  5124 just shows a blank screen (after selecting the partition to boot).  In both cases I am using a config.plist that works with Clover 5118, plus the quirks section from config_sample.plist.  I've tried all the obvious things and am running out of ideas.

Hardware is a GA-Z370P D3 and a Core i5 8600 with integrated graphics.  Bios is revision F10.

**Comment by mgrandinetti** [comment]
> > after UPDATE I lock my system to
> > LOG:EXITSB:START
> > seem a problem with bootx64.efi. If I change this all works again
> > thank in advance
> 
> May i know how did you change the bootx64.efi?

restored old bootx64.efui , return to pre release 5123

**Comment by i0ntempest** [comment]
> > tuck after updating. I get "not found returned from datahubdxe.efi", then after selecting Catalina it sticks at "[EB]#LOG:EXITBS:START]".
> 
> try remove datahubdxe.efi and this error will disappear

Thanks, but removing this file (thus this error) still doesn't allow my OS to boot.

**Comment by syah769** [comment]
> > > after UPDATE I lock my system to
> > > LOG:EXITSB:START
> > > seem a problem with bootx64.efi. If I change this all works again
> > > thank in advance
> > 
> > 
> > May i know how did you change the bootx64.efi?
> 
> restored old bootx64.efui , return to pre release 5123

To be honest, seriously I don't know how to restored the old boot efi. Sorry my my friend, hmm

**Comment by i0ntempest** [comment]
@syah769 If you installed the new Clover using the pkg installer, /EFI-Backups is automatically created and all contents of your EFI folder is copied into it before the installer touches anything. You can restore it if you can gain access to your root partition. And in the future ALWAYS keep a working EFI on a USB drive or something in case something like this happens.

**Comment by syah769** [comment]
> @syah769 If you installed the new Clover using the pkg installer, /EFI-Backups is automatically created and all contents of your EFI folder is copied into it before the installer touches anything. You can restore it if you can gain access to your root partition. And in the future ALWAYS keep a working EFI on a USB drive or something in case something like this happens.

![IMG_20201013_123618](https://user-images.githubusercontent.com/37147869/95816069-c941a780-0d50-11eb-9af6-d397f5278db9.jpg)

Hurm, how to restore? Any setting in this picture that I have to enter? If I click Boot MacOs, of course it will be stuck like the first picture on the top. Sorry for asking, I lost 😭😭

**Comment by i0ntempest** [comment]
If you don't have another Hackintosh or Mac and are not comfortable with the scary EFI shell, there're two ways:
1. Your computer should be able to boot Windows without Clover. Once in Windows get one of the softwares that can read apfs in Windows (Paragon APFS or UFS Explorer, both have a trial period) then recover the EFI backup.
2. Take your HDD/SSD out, grab an adapter for it and a USB drive, go to somewhere that has Macs, pop them in and do the recovery.

**Comment by syah769** [comment]
> If you don't have another Hackintosh or Mac and are not comfortable with the scary EFI shell, there're two ways:
> 
> 1. Your computer should be able to boot Windows without Clover. Once in Windows get one of the softwares that can read apfs in Windows (Paragon APFS or UFS Explorer, both have a trial period) then recover the EFI backup.
> 2. Take your HDD/SSD out, grab an adapter for it and a USB drive, go to somewhere that has Macs, pop them in and do the recovery.

 

I see, alright. Thank you buddy 👍😀

**Comment by zty199** [comment]
> I am, as yet, unable to boot Catalina with either 5123 or 5124. 5123 starts to boot and then freezes early in the boot process. 5124 just shows a blank screen (after selecting the partition to boot). In both cases I am using a config.plist that works with Clover 5118, plus the quirks section from config_sample.plist. I've tried all the obvious things and am running out of ideas.
> 
> Hardware is a GA-Z370P D3 and a Core i5 8600 with integrated graphics. Bios is revision F10.

You can try to add boot-args "npci=0x2000" and see if it gets any help...... I successfully boot into Big Sur after adding this boot-arg, though I don't know how it works......

**Comment by mwahh** [comment]
> You can try to add boot-args "npci=0x2000" and see if it gets any help...... I successfully boot into Big Sur after adding this boot-arg, though I don't know how it works......

Thanks, but no change.

**Comment by SavageAUS** [comment]
If this issue is still ongoing check insanelymac clover general discussion for answers. If issue is resolved please mark it as such.

**Comment by Noodle05** [comment]
Link to insanelymac discussion thread?

**Comment by hyperNURb** [comment]
@Noodle05 https://www.insanelymac.com/forum/topic/284656-clover-general-discussion/?page=957

**Comment by Noodle05** [comment]
@hyperNURb That is a generic discussion. Not for specific case. Easily lost in so many different topics/issues.

**Comment by malhal** [comment]
I'm sad the update is broken again like it was a few months ago and I got caught out for updating without checking here first. My question why not pull the update as soon as the issue was posted?

**Comment by SergeySlice** [comment]
There are several different issues mostly resolved in revision 5125.
Please don't create a thread like "I can't boot" - "I also can't".
Each issue must be specific with enough information for developers.

**Comment by hyperNURb** [comment]
@SergeySlice sorry and thank you 🙏

**Comment by SergioSuarezDev** [comment]
same here, after update blank screen on mojave

**Comment by cyberfunk** [comment]
Return to release 5122 and forget you had any problems. 5123 forward is buggy and or requires fixes.

**Comment by malhal** [comment]
Gave it one last chance today, upgraded from r5122 to r5126 hoping the issues were fixed but now gets stuck on small white apple logo. I'm done, switching to OpenCore.

**Comment by cyberfunk** [comment]
> Gave it one last chance today, upgraded from r5122 to r5126 hoping the issues were fixed but now gets stuck on small white apple logo. I'm done, switching to OpenCore.

I highly recommend OpenCore! I've been running it for the past few weeks and its been incredible.

**Comment by malhal** [comment]
Thanks I switched to OpenCore, the guides are like an infinite loop sometimes but very satisfying to get through it. I used OpenCore Configurator against their advice but I think it made it much simpler. Native startup disk selection and real disk icons in the boot chooser are a couple of things I'm enjoying.

**Comment by getsueineko** [comment]
> > Gave it one last chance today, upgraded from r5122 to r5126 hoping the issues were fixed but now gets stuck on small white apple logo. I'm done, switching to OpenCore.
> 
> I highly recommend OpenCore! I've been running it for the past few weeks and its been incredible.

OpenCore is not for all. It kills my GA-Z97X-SLI and I needed recover BIOS from backup chip :)

**Comment by cyberfunk** [comment]
> > > Gave it one last chance today, upgraded from r5122 to r5126 hoping the issues were fixed but now gets stuck on small white apple logo. I'm done, switching to OpenCore.
> > 
> > 
> > I highly recommend OpenCore! I've been running it for the past few weeks and its been incredible.
> 
> OpenCore is not for all. It kills my GA-Z97X-SLI and I needed recover BIOS from backup chip :)

After a few months with OpenCore I agree. It worked relatively well for a while but I noticed issues cropping up like QuickLook was breaking and other nagging problems. I've reverted back to Clover and my computer is a dream on Catalina. Rock solid. I still can't update past Clover 5122 but hoping to find a fix soon.
